# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=500)),
                ('Times', models.CharField(max_length=100)),
                ('PictureLink', models.CharField(max_length=3000)),
                ('Description', models.CharField(max_length=40000)),
                ('Location', models.CharField(max_length=3000)),
            ],
        ),
    ]
