# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
