# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='AgeRestriction',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='WebsiteLink',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
