# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-30 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Price',
            new_name='AdmissionFee',
        ),
    ]
